# Generated by Django 3.2.7 on 2021-09-24 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageUpload',
        ),
    ]
