# Generated by Django 3.2.7 on 2021-09-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210921_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='author',
        ),
    ]
