# Generated by Django 3.2.7 on 2021-09-24 15:05

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20210924_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='ranid',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
