# Generated by Django 3.2.7 on 2021-09-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210924_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
