# Generated by Django 3.2.7 on 2021-09-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_imageupload_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='ranid',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='user',
        ),
    ]
