# Generated by Django 3.2.7 on 2021-09-24 16:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210924_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_to),
        ),
    ]
